const $=id=>document.getElementById(id);
const PUBLIC_WS='wss://api.derivws.com/trading/v1/options/ws/public';
const CLIENT_ID='345Q6O96H6J8ANmWhmGkX';
const REDIRECT='https://sani-arb.vercel.app/callback';
const STORE='sani_arb_discovery_v3';
const S={ws:null,pending:new Map(),req:3000,authenticated:false,demoAccount:null,connectedDemo:false,scanning:false,killed:false,executing:false,tournament:false,symbols:[],contracts:new Map(),candidates:[],stats:new Map(),index:0,round:0,best:null,activePair:null};
const persisted=(()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return{}}})();
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const usd=v=>Number.isFinite(v)?`$${v.toFixed(4)}`:'—';
const pnl=v=>Number.isFinite(v)?`${v>0?'+':v<0?'-':''}$${Math.abs(v).toFixed(4)}`:'—';
function log(m,l=''){const d=document.createElement('div');d.className=l;d.textContent=`[${new Date().toLocaleTimeString()}] ${m}`;$('log').prepend(d)}
function status(t,d,tone='neutral'){$('statusText').textContent=t;$('statusDetail').textContent=d;$('modePill').className=`pill ${tone}`;$('modePill').textContent=S.killed?'STOPPED':S.connectedDemo?(S.tournament?'DEMO TOURNAMENT':'DERIV DEMO'):S.scanning?'PUBLIC DISCOVERY':'IDLE'}
function cfg(){return{payout:Number($('targetPayout').value),min:Number($('minEdge').value),buffer:Number($('safetyBuffer').value),delay:Math.max(250,Number($('scanDelay').value)||750),stable:Math.max(1,Number($('stableChecks').value)||3),eval:Math.max(5,Number($('evaluationPairs').value)||20),risk:$('includeRiskPairs').checked,drop:$('autoDrop').checked}}
function send(o){if(!S.ws||S.ws.readyState!==WebSocket.OPEN)throw Error('WebSocket not connected');S.ws.send(JSON.stringify(o))}
function req(o,timeout=9000){const id=++S.req;o.req_id=id;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{S.pending.delete(id);reject(Error('Deriv request timed out'))},timeout);S.pending.set(id,{resolve,reject,timer});try{send(o)}catch(e){clearTimeout(timer);S.pending.delete(id);reject(e)}})}
function onMsg(ev){let m;try{m=JSON.parse(ev.data)}catch{return}const p=S.pending.get(m.req_id);if(m.error){if(p){clearTimeout(p.timer);S.pending.delete(m.req_id);p.reject(Error(m.error.message||m.error.code||'Deriv error'))}else log(m.error.message||m.error.code,'bad');return}if(p){clearTimeout(p.timer);S.pending.delete(m.req_id);p.resolve(m)}if(m.msg_type==='proposal_open_contract')contractUpdate(m)}
async function openSocket(url){closeSocket();return new Promise((resolve,reject)=>{const ws=new WebSocket(url),timer=setTimeout(()=>{try{ws.close()}catch{}reject(Error('Connection timeout'))},10000);ws.onopen=()=>{clearTimeout(timer);S.ws=ws;ws.onmessage=onMsg;resolve()};ws.onerror=()=>{clearTimeout(timer);reject(Error('Could not open Deriv WebSocket'))};ws.onclose=()=>{if(S.ws===ws){S.ws=null;if(S.scanning){S.scanning=false;$('startBtn').disabled=false;$('stopBtn').disabled=true}if(S.connectedDemo){S.connectedDemo=false;S.tournament=false;$('tournamentEnabled').checked=false;$('tournamentEnabled').disabled=true}status('Disconnected','Deriv WebSocket closed.','risk')}}})}
function closeSocket(){if(S.ws)try{S.ws.close()}catch{}S.ws=null;S.pending.forEach(x=>{clearTimeout(x.timer);x.reject(Error('Connection closed'))});S.pending.clear()}
function stat(id){if(S.stats.has(id))return S.stats.get(id);const p=persisted[id]||{};const s={scans:+p.scans||0,positive:+p.positive||0,consecutive:0,edgeSum:+p.edgeSum||0,lastEdge:Number.isFinite(+p.lastEdge)?+p.lastEdge:null,bestEdge:Number.isFinite(+p.bestEdge)?+p.bestEdge:null,attempts:+p.attempts||0,paired:+p.paired||0,legFail:+p.legFail||0,settled:+p.settled||0,pnl:+p.pnl||0,wins:+p.wins||0,errors:+p.errors||0,dropped:!!p.dropped};S.stats.set(id,s);return s}
function save(){const o={};S.stats.forEach((s,id)=>o[id]={scans:s.scans,positive:s.positive,edgeSum:s.edgeSum,lastEdge:s.lastEdge,bestEdge:s.bestEdge,attempts:s.attempts,paired:s.paired,legFail:s.legFail,settled:s.settled,pnl:s.pnl,wins:s.wins,errors:s.errors,dropped:s.dropped});localStorage.setItem(STORE,JSON.stringify(o))}
function synthetic(r){const h=`${r.market||''} ${r.submarket||''} ${r.underlying_symbol_name||''} ${r.underlying_symbol_type||''}`.toLowerCase(),c=r.underlying_symbol||'';return h.includes('synthetic')||h.includes('volatility')||/^(R_|1HZ|BOOM|CRASH|JD)/i.test(c)}
function add(sym,key,name,a,b,risk,opt={}){const c={id:`${sym.code}:${key}`,symbol:sym.code,symbolName:sym.name,pip:sym.pip,name,a,b,risk,duration:opt.duration??1,unit:opt.unit??'t',barrierA:opt.barrierA,barrierB:opt.barrierB,barrier2A:opt.barrier2A,barrier2B:opt.barrier2B};S.candidates.push(c);stat(c.id)}
function build(sym,set){const has=(...x)=>x.every(v=>set.has(v));if(has('DIGITEVEN','DIGITODD'))add(sym,'evenodd','Even / Odd','DIGITEVEN','DIGITODD','exact');if(has('DIGITMATCH','DIGITDIFF'))for(let d=0;d<10;d++)add(sym,`matchdiff${d}`,`Match ${d} / Diff ${d}`,'DIGITMATCH','DIGITDIFF','exact',{barrierA:String(d),barrierB:String(d)});if(has('DIGITOVER','DIGITUNDER'))for(let d=0;d<9;d++)add(sym,`overunder${d}`,`Over ${d} / Under ${d+1}`,'DIGITOVER','DIGITUNDER','exact',{barrierA:String(d),barrierB:String(d+1)});if(has('CALL','PUT'))add(sym,'risefall','Rise / Fall','CALL','PUT','gap',{duration:5});if(has('ASIANU','ASIAND'))add(sym,'asian','Asian Up / Down','ASIANU','ASIAND','gap',{duration:5});if(has('RESETCALL','RESETPUT'))add(sym,'reset','Reset Call / Put','RESETCALL','RESETPUT','gap',{duration:5});if(has('ONETOUCH','NOTOUCH'))add(sym,'touch','Touch / No Touch','ONETOUCH','NOTOUCH','start-sync',{duration:2,unit:'m',barrierA:'+0.5',barrierB:'+0.5'});if(has('EXPIRYRANGE','EXPIRYMISS'))add(sym,'ends','Ends Between / Outside','EXPIRYRANGE','EXPIRYMISS','barrier-gap',{duration:2,unit:'m',barrierA:'+0.5',barrierB:'+0.5',barrier2A:'-0.5',barrier2B:'-0.5'});if(has('HIGHER','LOWER'))add(sym,'higherlower','Higher / Lower','HIGHER','LOWER','gap',{duration:2,unit:'m',barrierA:'+0.5',barrierB:'-0.5'})}
async function universe(){status('Loading universe','Reading active symbols and available contracts.');const a=await req({active_symbols:'brief'},12000);const rows=Array.isArray(a.active_symbols)?a.active_symbols:[];S.symbols=rows.filter(synthetic).map(r=>({code:r.underlying_symbol,name:r.underlying_symbol_name||r.underlying_symbol,pip:+r.pip_size||.01})).filter(x=>x.code);S.contracts.clear();S.candidates=[];let total=0;for(const sym of S.symbols){try{const r=await req({contracts_for:sym.code},10000);const av=r?.contracts_for?.available||[];const types=[...new Set(av.map(x=>x.contract_type).filter(Boolean))].sort();S.contracts.set(sym.code,types);total+=types.length;build(sym,new Set(types))}catch(e){log(`${sym.name}: contracts_for ${e.message}`,'warn')}}$('symbolCount').textContent=S.symbols.length;$('contractCount').textContent=total;$('candidateCount').textContent=S.candidates.length;catalog();leader();log(`Loaded ${S.symbols.length} symbols, ${total} contract listings, ${S.candidates.length} pair configurations.`,'good')}
function catalog(){const box=$('contractCatalog');box.replaceChildren();if(!S.contracts.size){box.innerHTML='<p class="muted small">No catalogue yet.</p>';return}for(const sym of S.symbols){const types=S.contracts.get(sym.code);if(!types?.length)continue;const g=document.createElement('div');g.className='catalogGroup';const strong=document.createElement('strong');strong.textContent=sym.name;const tags=document.createElement('div');tags.className='catalogTags';types.forEach(t=>{const s=document.createElement('span');s.textContent=t;tags.append(s)});g.append(strong,tags);box.append(g)}}
function proposal(c,type,barrier,barrier2){const o={proposal:1,amount:cfg().payout,basis:'payout',contract_type:type,currency:'USD',duration:c.duration,duration_unit:c.unit,underlying_symbol:c.symbol};if(barrier!==undefined)o.barrier=barrier;if(barrier2!==undefined)o.barrier2=barrier2;return o}
async function quote(c){const t=Date.now();const [ra,rb]=await Promise.all([req(proposal(c,c.a,c.barrierA,c.barrier2A),7000),req(proposal(c,c.b,c.barrierB,c.barrier2B),7000)]);const pa=ra.proposal,pb=rb.proposal;if(!pa?.id||!pb?.id)throw Error('Missing proposal ID');const A={id:pa.id,ask:n(pa.ask_price),payout:n(pa.payout),time:Date.now()},B={id:pb.id,ask:n(pb.ask_price),payout:n(pb.payout),time:Date.now()};if([A.ask,A.payout,B.ask,B.payout].some(x=>x===null))throw Error('Incomplete quote');const cost=A.ask+B.ask,floor=Math.min(A.payout,B.payout),edge=floor-cost;return{c,A,B,cost,floor,edge,skew:Date.now()-t}}
function live(q){S.best=q;$('legAName').textContent=q.c.a;$('legBName').textContent=q.c.b;$('legAAsk').textContent=usd(q.A.ask);$('legAPayout').textContent=usd(q.A.payout);$('legBAsk').textContent=usd(q.B.ask);$('legBPayout').textContent=usd(q.B.payout);$('livePairName').textContent=`${q.c.name} · ${q.c.symbolName}`;$('combinedCost').textContent=usd(q.cost);$('quotedEdge').textContent=pnl(q.edge);$('quoteSkew').textContent=`${q.skew} ms`;if(!S.best||q.edge>S.best.edge){S.best=q}$('bestEdge').textContent=pnl(q.edge);$('bestPair').textContent=`${q.c.name} · ${q.c.symbolName}`}
function verdict(c,s){if(s.dropped)return'DROP';if(s.settled>=cfg().eval){if(s.pnl>0&&s.legFail===0)return'KEEP';if(s.pnl<0)return'DROP';return'WATCH'}if(s.settled>0)return'WATCH';return'SCAN'}
function maybeDrop(c,s){if(cfg().drop&&s.settled>=cfg().eval&&s.pnl<0)s.dropped=true}
function leader(){const body=$('leaderboardBody');const rows=S.candidates.map(c=>({c,s:stat(c.id)})).sort((x,y)=>(y.s.pnl-x.s.pnl)||((y.s.lastEdge??-999)-(x.s.lastEdge??-999))).slice(0,100);body.replaceChildren();if(!rows.length){body.innerHTML='<tr><td colspan="10" class="empty">No evidence yet.</td></tr>';return}rows.forEach((x,i)=>{const v=verdict(x.c,x.s),tr=document.createElement('tr'),fill=x.s.attempts?`${((x.s.paired/x.s.attempts)*100).toFixed(0)}%`:'—';tr.innerHTML=`<td>${i+1}</td><td>${x.c.name}</td><td>${x.c.symbolName}</td><td>${x.c.risk}</td><td>${pnl(x.s.lastEdge)}</td><td>${x.s.scans}</td><td>${x.s.settled}/${x.s.attempts}</td><td>${fill}</td><td>${pnl(x.s.pnl)}</td><td><span class="badge ${v.toLowerCase()}">${v}</span></td>`;body.append(tr)});$('settledCount').textContent=[...S.stats.values()].reduce((a,s)=>a+s.settled,0)}
async function scanOne(c){const s=stat(c.id);if(s.dropped)return;try{const q=await quote(c);s.scans++;s.lastEdge=q.edge;s.edgeSum+=q.edge;if(s.bestEdge===null||q.edge>s.bestEdge)s.bestEdge=q.edge;if(q.edge>=cfg().min){s.positive++;s.consecutive++}else s.consecutive=0;live(q);save();leader();if(S.connectedDemo&&S.tournament&&!S.executing&&!S.activePair&&q.edge>=cfg().min+cfg().buffer&&s.consecutive>=cfg().stable&&(!['exact'].includes(c.risk)?cfg().risk:true))await execute(c,s)}catch(e){s.errors++;s.consecutive=0;if(s.errors<3)log(`${c.name} · ${c.symbolName}: ${e.message}`,'warn')}}
async function loop(){while(S.scanning&&!S.killed){if(!S.candidates.length){await wait(1000);continue}const c=S.candidates[S.index%S.candidates.length];S.index++;if(S.index%S.candidates.length===0){S.round++;$('roundCount').textContent=S.round}await scanOne(c);await wait(cfg().delay)} }
async function start(){const c=cfg();if(!Number.isFinite(c.payout)||c.payout<=0)throw Error('Target payout must be positive');S.killed=false;if(!S.ws)await openSocket(PUBLIC_WS);if(!S.candidates.length)await universe();S.scanning=true;$('startBtn').disabled=true;$('stopBtn').disabled=false;status('Discovery running',`Scanning ${S.candidates.length} configurations across ${S.symbols.length} symbols.`,'live');loop().catch(e=>{log(e.message,'bad');stop()})}
function stop(){S.scanning=false;$('startBtn').disabled=false;$('stopBtn').disabled=true;status('Discovery stopped','No new scans or demo entries will be sent.');log('Discovery stopped.')}
function emergencyStop(reason='Emergency stop pressed'){S.killed=true;S.scanning=false;S.tournament=false;$('tournamentEnabled').checked=false;$('startBtn').disabled=false;$('stopBtn').disabled=true;status('ENGINE STOPPED',reason,'risk');log(reason,'bad')}
async function buy(p,label){const r=await req({buy:p.id,price:p.ask},10000);const id=n(r?.buy?.contract_id),price=n(r?.buy?.buy_price)??p.ask;if(id===null)throw Error(`${label} missing contract id`);return{label,contractId:id,buyPrice:price,settled:false,profit:0}}
async function sell(id){return req({sell:id,price:0},7000)}
function monitor(pair,leg){pair.legs[leg.contractId]=leg;try{send({proposal_open_contract:1,contract_id:leg.contractId,subscribe:1,req_id:++S.req})}catch(e){log(`Monitor ${leg.contractId}: ${e.message}`,'warn')}}
async function execute(c,s){if(S.executing||S.activePair||!S.connectedDemo)return;S.executing=true;try{const q=await quote(c);if(q.edge<cfg().min+cfg().buffer)throw Error('Edge disappeared on execution re-quote');s.attempts++;status('Submitting twin legs',`${c.name}: quoted edge ${pnl(q.edge)}.`,'armed');const r=await Promise.allSettled([buy(q.A,'A'),buy(q.B,'B')]);const ok=r.filter(x=>x.status==='fulfilled').map(x=>x.value);if(ok.length===2){s.paired++;const pair={candidateId:c.id,c,legs:{}};ok.forEach(x=>monitor(pair,x));S.activePair=pair;log(`PAIR OPEN: ${c.name} · contracts ${ok.map(x=>x.contractId).join(' + ')}`,'good');status('Demo pair open','Both legs filled. Waiting for settlement.','live')}else if(ok.length===1){s.legFail++;S.tournament=false;$('tournamentEnabled').checked=false;const lone=ok[0];log(`LEG FAILURE: ${lone.contractId}. Emergency sell.`, 'bad');let result=0;try{const sr=await sell(lone.contractId);const sold=n(sr?.sell?.sold_for);if(sold!==null)result=sold-lone.buyPrice}catch(e){log(`Emergency sell failed: ${e.message}`,'bad')}s.settled++;s.pnl+=result;S.killed=true;S.scanning=false;status('UNHEDGED · STOPPED',`Emergency realized P/L ${pnl(result)}.`,'risk')}else log('Both demo buys rejected. No confirmed position.','warn');s.consecutive=0;save();leader()}catch(e){log(`Execution: ${e.message}`,'bad')}finally{S.executing=false}}
function contractUpdate(m){const pair=S.activePair,c=m?.proposal_open_contract,id=n(c?.contract_id);if(!pair||id===null||!pair.legs[id])return;const st=String(c.status||'').toLowerCase(),done=!!c.is_sold||['won','lost','sold','expired'].includes(st);if(!done||pair.legs[id].settled)return;pair.legs[id].settled=true;pair.legs[id].profit=n(c.profit)??0;log(`${pair.legs[id].label} settled ${pnl(pair.legs[id].profit)} · ${id}`,pair.legs[id].profit>=0?'good':'bad');const legs=Object.values(pair.legs);if(legs.length===2&&legs.every(x=>x.settled)){const total=legs.reduce((a,x)=>a+x.profit,0),s=stat(pair.candidateId);s.settled++;s.pnl+=total;if(total>0)s.wins++;maybeDrop(pair.c,s);save();leader();log(`PAIR SETTLED: ${pair.c.name} actual ${pnl(total)}`,total>0?'good':'bad');status('Demo pair settled',`${pair.c.name}: realized ${pnl(total)}.` ,total>0?'live':'neutral');S.activePair=null}}
function b64(b){return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function login(){const r=crypto.getRandomValues(new Uint8Array(64)),alpha='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~',ver=Array.from(r,x=>alpha[x%alpha.length]).join(''),dig=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ver)),challenge=b64(new Uint8Array(dig)),state=Array.from(crypto.getRandomValues(new Uint8Array(24)),x=>x.toString(16).padStart(2,'0')).join('');sessionStorage.setItem('sani_pkce_verifier',ver);sessionStorage.setItem('sani_oauth_state',state);const p=new URLSearchParams({response_type:'code',client_id:CLIENT_ID,redirect_uri:REDIRECT,scope:'trade',state,code_challenge:challenge,code_challenge_method:'S256'});location.assign(`https://auth.deriv.com/oauth2/auth?${p}`)}
async function oauth(){const p=new URLSearchParams(location.search);if(!p.get('code')&&!p.get('error'))return;if(p.get('error'))throw Error(p.get('error_description')||p.get('error'));const code=p.get('code'),returned=p.get('state'),expected=sessionStorage.getItem('sani_oauth_state'),ver=sessionStorage.getItem('sani_pkce_verifier');if(!code||returned!==expected||!ver)throw Error('OAuth validation failed');const r=await fetch('/api/oauth-exchange',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({code,codeVerifier:ver,redirectUri:REDIRECT})}),b=await r.json();if(!r.ok)throw Error(b.error||'OAuth exchange failed');sessionStorage.removeItem('sani_oauth_state');sessionStorage.removeItem('sani_pkce_verifier');history.replaceState({},'','/');log('Deriv OAuth completed.','good')}
function renderLogin(){if(S.authenticated&&S.demoAccount){$('loginTitle').textContent='Logged in · Demo ready';$('loginDetail').textContent=`${S.demoAccount.account_id} · ${S.demoAccount.currency||'USD'} · balance ${S.demoAccount.balance??'—'}`;$('loginDerivBtn').hidden=true;$('logoutDerivBtn').hidden=false;$('connectDemoBtn').disabled=S.connectedDemo}else{$('loginTitle').textContent='Not logged in';$('loginDetail').textContent='Login with Deriv to enable demo tournament.';$('loginDerivBtn').hidden=false;$('logoutDerivBtn').hidden=true;$('connectDemoBtn').disabled=true}}
async function session(){const r=await fetch('/api/session',{credentials:'same-origin'}),b=await r.json();S.authenticated=!!(r.ok&&b.authenticated&&b.demoAccount);S.demoAccount=S.authenticated?b.demoAccount:null;renderLogin()}
async function demoUrl(){const r=await fetch('/api/demo-otp',{method:'POST',credentials:'same-origin'}),b=await r.json();if(!r.ok)throw Error(b.error||'Demo OTP failed');if(!b.url||!b.url.includes('/ws/demo'))throw Error('Safety lock rejected non-demo socket');return b.url}
async function connectDemo(){if(!S.authenticated)throw Error('Login first');const was=S.scanning;S.scanning=false;const url=await demoUrl();await openSocket(url);S.connectedDemo=true;$('connectDemoBtn').disabled=true;$('tournamentEnabled').disabled=false;$('emergencyBtn').disabled=false;if(!S.candidates.length)await universe();if(was){S.scanning=true;$('startBtn').disabled=true;$('stopBtn').disabled=false;loop()}status('Deriv Demo connected','Discovery can run. Tournament remains off until enabled.','live');log(`Connected to ${S.demoAccount.account_id}. Demo only.`,'good')}
async function logout(){emergencyStop('Deriv session logged out');closeSocket();await fetch('/api/logout',{method:'POST',credentials:'same-origin'});S.authenticated=false;S.demoAccount=null;S.connectedDemo=false;$('tournamentEnabled').disabled=true;renderLogin()}
function reset(){localStorage.removeItem(STORE);Object.keys(persisted).forEach(k=>delete persisted[k]);S.stats.clear();S.candidates.forEach(c=>stat(c.id));S.round=0;$('roundCount').textContent='0';leader();log('Results reset.')}
$('startBtn').onclick=()=>start().catch(e=>{log(e.message,'bad');status('Discovery error',e.message,'risk')});$('stopBtn').onclick=stop;$('emergencyBtn').onclick=()=>emergencyStop();$('resetResultsBtn').onclick=reset;$('clearLogBtn').onclick=()=>$('log').replaceChildren();$('loginDerivBtn').onclick=()=>login().catch(e=>log(e.message,'bad'));$('connectDemoBtn').onclick=()=>connectDemo().catch(e=>{log(e.message,'bad');status('Demo connection failed',e.message,'risk')});$('logoutDerivBtn').onclick=()=>logout().catch(e=>log(e.message,'bad'));$('tournamentEnabled').onchange=e=>{S.tournament=e.target.checked;S.killed=false;log(`Demo tournament ${S.tournament?'ENABLED':'disabled'}.`,S.tournament?'warn':'');if(S.tournament&&!S.scanning)start().catch(x=>log(x.message,'bad'));status(S.tournament?'Demo tournament armed':'Deriv Demo connected',S.tournament?'Qualified pairs may execute one at a time.':'No demo trades will be sent.',S.tournament?'armed':'live')};
(async()=>{try{await oauth()}catch(e){history.replaceState({},'','/');log(`Login failed: ${e.message}`,'bad')}try{await session()}catch(e){log(`Session: ${e.message}`,'warn');renderLogin()}status('Idle','Start discovery to load Synthetic Indices and available contracts.');log('Discovery Lab loaded. Demo-only execution; evidence persists in this browser.')})();