const $=id=>document.getElementById(id);
const STATS='sani_harvest_aligned_v1',COOLDOWN='sani_harvest_cooldown_until',DAY='sani_harvest_day',COUNT='sani_harvest_sessions_today';
const S={ws:null,pending:new Map(),req:12000,stats:{},account:null,candidates:[],running:false,entries:0,settled:0,pnl:0,attempts:0,launching:0,pairs:new Map(),contractMap:new Map(),cursor:0,pool:[],heartbeat:null,goalReached:false,generation:0,wave:0};
const num=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const money=v=>`${v>0?'+':v<0?'-':''}$${Math.abs(v||0).toFixed(4)}`;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function log(m,c=''){const d=document.createElement('div');d.className=c;d.textContent=`[${new Date().toLocaleTimeString()}] ${m}`;$('log').prepend(d)}
function setStatus(t,d,c=''){$('status').textContent=t;$('detail').textContent=d;$('status').className=c}
function loadStats(){try{S.stats=JSON.parse(localStorage.getItem(STATS)||'{}')}catch{S.stats={}}}
function saveStats(){localStorage.setItem(STATS,JSON.stringify(S.stats))}
function st(id){return S.stats[id]||(S.stats[id]={scans:0,positive:0,lastEdge:null,lastNorm:null,bestEdge:null,attempts:0,paired:0,legFail:0,settled:0,pnl:0,wins:0,doubleLoss:0,equalityLoss:0})}
function cfg(){return{payout:Math.max(.35,Number($('payout').value)||1),min:Math.max(0,Number($('minEdge').value)||.01),buffer:Math.max(0,Number($('buffer').value)||.005),goal:5,lossCap:-2,maxEntries:100,windows:4,expirySec:120}}
function dayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function sessionsToday(){if(localStorage.getItem(DAY)!==dayKey()){localStorage.setItem(DAY,dayKey());localStorage.setItem(COUNT,'0')}return Number(localStorage.getItem(COUNT)||0)}
function incSession(){const n=sessionsToday()+1;localStorage.setItem(COUNT,String(n));return n}
function cooldownUntil(){return Number(localStorage.getItem(COOLDOWN)||0)}
function setCooldown(ms,reason){const until=Date.now()+ms;localStorage.setItem(COOLDOWN,String(until));log(`${reason} Cooldown until ${new Date(until).toLocaleTimeString()}.`,'warn');updateCooldown()}
function updateCooldown(){const left=Math.max(0,cooldownUntil()-Date.now()),el=$('cooldown');if(left>0){const m=Math.floor(left/60000),s=Math.floor((left%60000)/1000);el.textContent=`${m}:${String(s).padStart(2,'0')}`;$('start').disabled=true}else{el.textContent='READY';if(!S.running&&sessionsToday()<5)$('start').disabled=false}$('sessionsToday').textContent=`${sessionsToday()}/5`}
setInterval(updateCooldown,1000);
function send(o){if(!S.ws||S.ws.readyState!==WebSocket.OPEN)throw Error('Demo WebSocket not connected');S.ws.send(JSON.stringify(o))}
function request(o,timeout=9000){const id=++S.req;o.req_id=id;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{S.pending.delete(id);reject(Error('Deriv request timed out'))},timeout);S.pending.set(id,{resolve,reject,timer});try{send(o)}catch(e){clearTimeout(timer);S.pending.delete(id);reject(e)}})}
function onMessage(ev){let m;try{m=JSON.parse(ev.data)}catch{return}const p=S.pending.get(m.req_id);if(m.error){if(p){clearTimeout(p.timer);S.pending.delete(m.req_id);p.reject(Error(m.error.message||m.error.code||'Deriv error'))}else log(m.error.message||m.error.code,'bad');return}if(p){clearTimeout(p.timer);S.pending.delete(m.req_id);p.resolve(m)}if(m.msg_type==='proposal_open_contract')contractUpdate(m)}
async function session(){const r=await fetch('/api/session',{credentials:'same-origin'}),b=await r.json();if(!r.ok||!b.authenticated||!b.demoAccount)throw Error('Please use Login with Deriv on this page.');S.account=b.demoAccount;$('account').textContent=`${b.demoAccount.account_id} · ${b.demoAccount.currency||'USD'} · ${b.demoAccount.balance??'—'} virtual balance`}
async function connect(){if(S.ws?.readyState===WebSocket.OPEN)return;const r=await fetch('/api/demo-otp',{method:'POST',credentials:'same-origin'}),b=await r.json();if(!r.ok)throw Error(b.error||'Demo OTP failed');if(!b.url||!b.url.includes('/ws/demo'))throw Error('Safety lock rejected non-demo endpoint');await new Promise((resolve,reject)=>{const ws=new WebSocket(b.url),timer=setTimeout(()=>reject(Error('Demo connection timeout')),10000);ws.onopen=()=>{clearTimeout(timer);S.ws=ws;ws.onmessage=onMessage;S.heartbeat=setInterval(()=>{try{send({ping:1,req_id:++S.req})}catch{}},30000);resolve()};ws.onerror=()=>reject(Error('Demo WebSocket failed'));ws.onclose=()=>{clearInterval(S.heartbeat);S.ws=null;S.generation++;if(S.running){S.running=false;setCooldown(5*60*1000,'Demo socket closed.');setStatus('5-MIN COOLDOWN','No new entries. Login unlocks after the technical cooldown.','warnText');$('stop').disabled=true}}});log('Connected to Deriv DEMO. Heartbeat active.','good')}
function candidate(sym,group){return{id:`aligned:${sym.code}:higherlower`,symbol:sym.code,symbolName:sym.name,group,name:'Higher / Lower · SAME BARRIER',a:'HIGHER',b:'LOWER',pip:sym.pip||0.01}}
async function universe(){const a=await request({active_symbols:'brief'},12000),rows=Array.isArray(a.active_symbols)?a.active_symbols:[],seen=new Map();for(const r of rows){const code=r.underlying_symbol,name=r.underlying_symbol_name||code,pip=num(r.pip_size)||0.01;if(code&&!seen.has(code))seen.set(code,{code,name,pip})}const wanted=[['Core Standard','Volatility 25 Index'],['Core Standard','Volatility 100 Index'],['Fast Confirm','Volatility 10 (1s) Index'],['Bull','Bull Market Index']];S.candidates=[];for(const [group,label] of wanted){const sym=[...seen.values()].find(x=>x.name===label);if(!sym){log(`Missing market: ${label}`,'warn');continue}try{const r=await request({contracts_for:sym.code},9000),types=new Set((r?.contracts_for?.available||[]).map(x=>x.contract_type));if(types.has('HIGHER')&&types.has('LOWER'))S.candidates.push(candidate(sym,group));else log(`${label}: Higher/Lower unavailable`,'warn')}catch(e){log(`${label}: ${e.message}`,'warn')}}$('universe').textContent=`${S.candidates.length} aligned markets · same barrier + same expiry`;S.pool=[...S.candidates];renderBoard()}
async function latestTick(c){const r=await request({ticks:c.symbol},7000),q=num(r?.tick?.quote),epoch=num(r?.tick?.epoch);if(q===null||epoch===null)throw Error('Could not read live tick for barrier alignment');return{quote:q,epoch}}
function decimals(pip){const s=String(pip);if(s.includes('e-'))return Number(s.split('e-')[1]);const i=s.indexOf('.');return i<0?0:s.length-i-1}
function alignBarrier(spot,pip){const d=decimals(pip);const step=pip||Math.pow(10,-d);const rounded=Math.round(spot/step)*step;return rounded.toFixed(d)}
function proposal(c,type,barrier,expiry){return{proposal:1,amount:cfg().payout,basis:'payout',contract_type:type,currency:S.account?.currency||'USD',date_expiry:expiry,underlying_symbol:c.symbol,barrier}}
async function alignedQuote(c){const tick=await latestTick(c),barrier=alignBarrier(tick.quote,c.pip),expiry=tick.epoch+cfg().expirySec;const [ra,rb]=await Promise.all([request(proposal(c,c.a,barrier,expiry),7000),request(proposal(c,c.b,barrier,expiry),7000)]),pa=ra.proposal,pb=rb.proposal,A={id:pa?.id,ask:num(pa?.ask_price),payout:num(pa?.payout)},B={id:pb?.id,ask:num(pb?.ask_price),payout:num(pb?.payout)};if(!A.id||!B.id||[A.ask,A.payout,B.ask,B.payout].some(v=>v===null))throw Error('Incomplete aligned quote');const payoutGap=Math.abs(A.payout-B.payout);if(payoutGap>0.005)throw Error(`Payout mismatch ${payoutGap.toFixed(4)}`);const cost=A.ask+B.ask,edge=Math.min(A.payout,B.payout)-cost,norm=1-(A.ask/A.payout)-(B.ask/B.payout);return{A,B,edge,norm,barrier,expiry,spot:tick.quote}}
async function buy(p,label){const r=await request({buy:p.id,price:p.ask},10000),id=num(r?.buy?.contract_id),buyPrice=num(r?.buy?.buy_price)??p.ask;if(id===null)throw Error('Buy missing contract ID');return{label,contractId:id,buyPrice,profit:0,settled:false,startTime:num(r?.buy?.start_time),purchaseTime:num(r?.buy?.purchase_time),shortcode:r?.buy?.shortcode||''}}
async function sell(id){return request({sell:id,price:0},7000)}
function nextCandidate(){const c=S.pool[S.cursor%S.pool.length];S.cursor++;return c}
function nextWindow(){const used=new Set([...S.pairs.values()].map(p=>p.window));for(let i=1;i<=cfg().windows;i++)if(!used.has(i))return i;return 1}
function monitor(pair,leg){pair.legs[leg.contractId]=leg;S.contractMap.set(leg.contractId,pair.id);send({proposal_open_contract:1,contract_id:leg.contractId,subscribe:1,req_id:++S.req})}
async function launch(gen){if(!S.running||S.goalReached||gen!==S.generation||S.entries+S.launching>cfg().maxEntries)return;const c=nextCandidate(),cs=st(c.id);try{const q=await alignedQuote(c);cs.scans++;cs.lastEdge=q.edge;cs.lastNorm=q.norm;cs.bestEdge=cs.bestEdge==null?q.edge:Math.max(cs.bestEdge,q.edge);if(q.edge<cfg().min+cfg().buffer||q.norm<=0){log(`${c.symbolName} skip · aligned edge ${money(q.edge)} · norm ${(q.norm*100).toFixed(3)}%`,'info');return}if(!S.running||gen!==S.generation)return;S.attempts++;cs.attempts++;const window=nextWindow();const r=await Promise.allSettled([buy(q.A,'A'),buy(q.B,'B')]);if(!S.running||gen!==S.generation){const filled=r.filter(x=>x.status==='fulfilled').map(x=>x.value);for(const leg of filled){try{await sell(leg.contractId)}catch{}}log(`${c.symbolName}: stop fired during buy; filled legs sent to emergency sell.`,'warn');return}const ok=r.filter(x=>x.status==='fulfilled').map(x=>x.value);if(ok.length===2){S.entries++;cs.paired++;const id=`W${S.wave}-P${S.entries}`,startSkew=(ok[0].startTime!==null&&ok[1].startTime!==null)?Math.abs(ok[0].startTime-ok[1].startTime):null,pair={id,window,c,legs:{},barrier:q.barrier,expiry:q.expiry,edge:q.edge,norm:q.norm,startSkew};S.pairs.set(id,pair);ok.forEach(x=>monitor(pair,x));log(`${id} OPEN · ${c.symbolName} · barrier ${q.barrier} · expiry ${new Date(q.expiry*1000).toLocaleTimeString()} · edge ${money(q.edge)} · norm ${(q.norm*100).toFixed(3)}%${startSkew!==null?` · start skew ${startSkew}s`:''}`,'good')}else if(ok.length===1){cs.legFail++;let result=-ok[0].buyPrice;try{const sr=await sell(ok[0].contractId),sold=num(sr?.sell?.sold_for);if(sold!==null)result=sold-ok[0].buyPrice}catch{}cs.settled++;cs.pnl+=result;S.pnl+=result;log(`Single-leg emergency ${money(result)}`,'bad')}saveStats();render()}catch(e){log(`${c.symbolName}: ${e.message}`,'warn')}}
function assessBeforeNextWave(){if(!S.running)return false;if(S.pnl>=cfg().goal){S.goalReached=true;S.running=false;S.generation++;incSession();setCooldown(60*60*1000,'Successful session complete.');setStatus('GOAL REACHED','+$5 settled P/L reached. Session locked for 60 minutes.','good');log('GRATEFUL STOP: +$5 reached after completed wave.','good');return false}if(S.pnl<=cfg().lossCap){S.running=false;S.generation++;incSession();setCooldown(60*60*1000,'Session loss cap reached.');setStatus('LOSS CAP','-$2 settled P/L reached. Session locked for 60 minutes.','bad');return false}if(S.entries>=cfg().maxEntries){S.running=false;S.generation++;incSession();setCooldown(60*60*1000,'100-entry safety cap reached.');setStatus('ENTRY CAP','100 paired entries reached. Session closed.','warnText');return false}return true}
function pumpWave(){if(!S.running||S.goalReached||S.pairs.size||S.launching)return;if(!assessBeforeNextWave())return;S.wave++;const remaining=cfg().maxEntries-S.entries,count=Math.min(cfg().windows,remaining);const gen=S.generation;log(`WAVE ${S.wave} · launching up to ${count} aligned pairs.`,'info');for(let i=0;i<count;i++){S.launching++;launch(gen).finally(()=>{S.launching--;render();if(S.running&&S.launching===0&&S.pairs.size===0)setTimeout(pumpWave,200)})}}
function contractUpdate(m){const c=m?.proposal_open_contract,id=num(c?.contract_id),pair=S.pairs.get(S.contractMap.get(id));if(!pair||!pair.legs[id])return;const leg=pair.legs[id];leg.profit=num(c.profit)??leg.profit;const done=!!c.is_sold||['won','lost','sold','expired'].includes(String(c.status||'').toLowerCase());if(done&&!leg.settled){leg.settled=true;log(`${pair.id} ${leg.label} ${money(leg.profit)}`,leg.profit>=0?'good':'bad')}const legs=Object.values(pair.legs);if(legs.length===2&&legs.every(x=>x.settled))finalize(pair);render()}
function finalize(pair){const total=Object.values(pair.legs).reduce((a,x)=>a+(x.profit||0),0),cs=st(pair.c.id);cs.settled++;cs.pnl+=total;if(total>0)cs.wins++;if(Object.values(pair.legs).every(x=>(x.profit||0)<0))cs.doubleLoss=(cs.doubleLoss||0)+1;S.pnl+=total;S.settled++;Object.values(pair.legs).forEach(x=>S.contractMap.delete(x.contractId));S.pairs.delete(pair.id);log(`${pair.id} SETTLED · ${pair.c.symbolName} · ${money(total)} · barrier ${pair.barrier}`,total>=0?'good':'bad');saveStats();render();if(S.running&&S.pairs.size===0&&S.launching===0){if(assessBeforeNextWave())setTimeout(pumpWave,250)}}
async function start(){updateCooldown();if(Date.now()<cooldownUntil())throw Error('Cooldown still active.');if(sessionsToday()>=5)throw Error('Daily session limit reached. Come back tomorrow.');await session();await connect();loadStats();await universe();if(!S.candidates.length)throw Error('Chosen markets unavailable right now.');S.running=true;S.goalReached=false;S.generation++;S.entries=S.settled=S.attempts=S.launching=0;S.pnl=0;S.cursor=0;S.wave=0;S.pairs.clear();S.contractMap.clear();$('start').disabled=true;$('stop').disabled=false;setStatus('ALIGNED TEST','Same barrier + same expiry. Only positive aligned quotes may enter.','good');log('SESSION START · ALIGNED HIGHER/LOWER · goal +$5 · loss cap -$2 · max 100 pairs.','good');render();pumpWave()}
function stop(){if(!S.running)return;S.running=false;S.generation++;incSession();setCooldown(60*60*1000,'Manual session stop.');$('stop').disabled=true;setStatus('STOPPED','Manual stop. Existing bought pairs remain monitored; no replacements can launch.','warnText')}
function render(){$('pnl').textContent=money(S.pnl);$('entries').textContent=`${S.entries}/100`;$('settled').textContent=String(S.settled);$('active').textContent=`${S.pairs.size}/4`;$('sessionsToday').textContent=`${sessionsToday()}/5`;const box=$('windowsGrid');box.replaceChildren();if(!S.pairs.size)box.innerHTML='<div class="empty">No open aligned pair windows.</div>';else[...S.pairs.values()].sort((a,b)=>a.window-b.window).forEach(p=>{const d=document.createElement('article');d.className='window';d.innerHTML=`<div><span>LANE ${p.window}</span><b>${p.c.group}</b></div><p>${p.c.symbolName}</p><small>SAME barrier ${p.barrier} · common expiry</small><div class="row"><span>Quoted edge</span><b>${money(p.edge)}</b></div><div class="row"><span>Live P/L</span><b>${money(Object.values(p.legs).reduce((a,x)=>a+(x.profit||0),0))}</b></div>`;box.append(d)});renderBoard();updateCooldown()}
function renderBoard(){const body=$('board'),rows=S.candidates.map(c=>({c,s:st(c.id)})).sort((a,b)=>(b.s.pnl||0)-(a.s.pnl||0));body.replaceChildren();if(!rows.length){body.innerHTML='<tr><td colspan="9" class="empty">Aligned markets load after connection.</td></tr>';return}rows.forEach((x,i)=>{const fill=x.s.attempts?`${Math.round(100*x.s.paired/x.s.attempts)}%`:'—',tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td>${x.c.group}</td><td>${x.c.symbolName}</td><td>${x.s.settled||0}</td><td>${x.s.wins||0}</td><td>${x.s.doubleLoss||0}</td><td>${fill}</td><td>${money(x.s.lastEdge||0)} <small>norm ${((x.s.lastNorm||0)*100).toFixed(3)}%</small></td><td>${money(x.s.pnl||0)}</td>`;body.append(tr)})}
$('start').onclick=()=>start().catch(e=>{setStatus('CANNOT START',e.message,'bad');log(e.message,'bad')});$('stop').onclick=stop;$('clear').onclick=()=>$('log').replaceChildren();(async()=>{loadStats();updateCooldown();try{await session();setStatus('READY','Aligned engine ready. Existing cooldown rules still apply.','good')}catch(e){setStatus('LOGIN REQUIRED','Use Login with Deriv on this page.','bad')}render()})();