const $=id=>document.getElementById(id);
const S={ws:null,pending:new Map(),req:3000,account:null,running:false,starting:false,generation:0,symbols:[],catalog:new Map(),eligible:[],symbolCursor:0,models:new Map(),modelStats:new Map(),quoted:0,structural:0,dropped:0,pnl:0,trades:0,wins:0,losses:0,sessionLossStreak:0,idleCycles:0,active:null,timer:null,current:null,heartbeat:null};
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const money=v=>`${v>0?'+':v<0?'-':''}$${Math.abs(v||0).toFixed(3)}`;
const pct=v=>Number.isFinite(v)?`${(v*100).toFixed(1)}%`:'—';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function log(t,c=''){const d=document.createElement('div');d.className=c;d.textContent=`[${new Date().toLocaleTimeString()}] ${t}`;$('log').prepend(d);while($('log').children.length>180)$('log').lastElementChild.remove()}
function phase(n){for(let i=1;i<=7;i++)$(`p${i}`)?.classList.toggle('on',i===n)}
function status(t,d,n=0){$('status').textContent=t;$('detail').textContent=d;if(n)phase(n)}
function stats(key){return S.modelStats.get(key)||{trades:0,wins:0,losses:0,pnl:0,lossStreak:0,dropped:false}}
function saveStats(key,v){S.modelStats.set(key,v)}
function setDecision(name,text,mode='rest'){S.current=S.current||{};$('decisionName').textContent=name;$('decisionText').textContent=text;$('decisionMode').textContent=mode.toUpperCase();$('decisionMode').className=`mode ${mode}`}
function render(){$('pnl').textContent=money(S.pnl);$('trades').textContent=String(S.trades);$('wl').textContent=`${S.wins} / ${S.losses}`;$('symbols').textContent=String(S.symbols.length);$('models').textContent=String(S.models.size);$('quoted').textContent=String(S.quoted);$('structural').textContent=String(S.structural);$('dropped').textContent=String(S.dropped);$('contractTypes').textContent=String(new Set([...S.catalog.values()].flatMap(x=>x.types)).size);$('scanPulse').textContent=S.running?'ACTIVE':S.active?'SETTLING':'IDLE';renderCurrent();renderTape()}
function renderCurrent(){const c=S.current;if(!c?.proposal){$('candidateTitle').textContent='Nothing selected yet';$('candidatePill').textContent='WAITING';$('candidateArea').innerHTML='<div class="box"><span>CONTRACT</span><strong>—</strong></div><div class="box"><span>SAMPLE</span><strong>—</strong></div><div class="box"><span>RECENT STABILITY</span><strong>—</strong></div><div class="box"><span>REALIZED P/L</span><strong>—</strong></div><div class="box"><span>STATUS</span><strong>—</strong></div>';$('breakEven').textContent=$('modelProb').textContent=$('confFloor').textContent=$('expectedEdge').textContent='—';return}const st=stats(c.key),q=c.proposal;$('candidateTitle').textContent=`${c.label} · ${c.symbolName}`;$('candidatePill').textContent=c.mode||'WATCH';$('candidateArea').innerHTML=`<div class="box"><span>CONTRACT</span><strong>${c.contractType}</strong></div><div class="box"><span>SAMPLE</span><strong>${c.sample}</strong></div><div class="box"><span>RECENT STABILITY</span><strong>${pct(c.recentP)}</strong></div><div class="box"><span>REALIZED P/L</span><strong>${money(st.pnl)}</strong></div><div class="box"><span>STATUS</span><strong>${st.dropped?'DROPPED':c.mode||'WATCH'}</strong></div>`;$('breakEven').textContent=pct(q.breakEven);$('modelProb').textContent=pct(c.p);$('confFloor').textContent=pct(c.lower);$('expectedEdge').textContent=money(q.expected)}
function renderTape(){const el=$('tradeTape');const rows=[...S.modelStats.entries()].filter(([,v])=>v.trades).sort((a,b)=>b[1].pnl-a[1].pnl).slice(0,8);el.innerHTML=rows.map(([k,v])=>`<div class="tradeLine"><span>${k}</span><strong class="${v.pnl>=0?'good':'bad'}">${v.wins}W/${v.losses}L · ${money(v.pnl)}${v.dropped?' · DROPPED':''}</strong></div>`).join('')}
function send(o){if(!S.ws||S.ws.readyState!==WebSocket.OPEN)throw Error('Demo WebSocket not connected');S.ws.send(JSON.stringify(o))}
function request(o,timeout=10000){const id=++S.req;o.req_id=id;return new Promise((resolve,reject)=>{const t=setTimeout(()=>{S.pending.delete(id);reject(Error('Deriv request timed out'))},timeout);S.pending.set(id,{resolve,reject,t});try{send(o)}catch(e){clearTimeout(t);S.pending.delete(id);reject(e)}})}
function onMessage(ev){let m;try{m=JSON.parse(ev.data)}catch{return}const p=S.pending.get(m.req_id);if(m.error){if(p){clearTimeout(p.t);S.pending.delete(m.req_id);p.reject(Error(m.error.message||m.error.code||'Deriv error'))}else log(m.error.message||m.error.code,'bad');return}if(p){clearTimeout(p.t);S.pending.delete(m.req_id);p.resolve(m)}if(m.msg_type==='proposal_open_contract')contractUpdate(m)}
async function loadSession(){const r=await fetch('/api/session',{credentials:'same-origin',cache:'no-store'}),b=await r.json().catch(()=>({}));if(!r.ok||!b.authenticated||!b.demoAccount)throw Error('Login with Deriv first.');S.account=b.demoAccount;$('account').textContent=`${b.demoAccount.account_id} · ${b.demoAccount.currency||'USD'} · Demo`}
async function connect(){if(S.ws?.readyState===WebSocket.OPEN)return;const r=await fetch('/api/demo-otp',{method:'POST',credentials:'same-origin'}),b=await r.json().catch(()=>({}));if(!r.ok||!b.url)throw Error(b.error||'Could not open Demo socket');await new Promise((resolve,reject)=>{let done=false;const ws=new WebSocket(b.url),timer=setTimeout(()=>{if(!done){done=true;reject(Error('Demo socket timeout'))}},10000);ws.onopen=()=>{if(done)return;done=true;clearTimeout(timer);S.ws=ws;ws.onmessage=onMessage;S.heartbeat=setInterval(()=>{try{send({ping:1,req_id:++S.req})}catch{}},30000);resolve()};ws.onerror=()=>{if(!done){done=true;clearTimeout(timer);reject(Error('Browser could not open Demo socket'))}};ws.onclose=()=>{clearInterval(S.heartbeat);S.ws=null;S.running=false;clearTimeout(S.timer);status('CONNECTION CLOSED','Demo connection closed. Sani stopped sending entries.');$('start').disabled=!!S.active;$('stop').disabled=true}});log('Connected to Deriv Demo.','good')}
async function mapUniverse(){status('MAPPING','Reading the full active-symbol and contract universe.',1);const a=await request({active_symbols:'brief'},12000),rows=Array.isArray(a.active_symbols)?a.active_symbols:[];S.symbols=rows.map(x=>({code:x.underlying_symbol,name:x.underlying_symbol_name||x.underlying_symbol,type:x.underlying_symbol_type||'',pip:num(x.pip_size)||0.01})).filter(x=>x.code);S.catalog.clear();let cursor=0;const workers=Array.from({length:8},async()=>{while(cursor<S.symbols.length){const s=S.symbols[cursor++];try{const r=await request({contracts_for:s.code},10000),available=Array.isArray(r?.contracts_for?.available)?r.contracts_for.available:[],types=[...new Set(available.map(x=>x.contract_type).filter(Boolean))];S.catalog.set(s.code,{symbol:s,types,available})}catch{S.catalog.set(s.code,{symbol:s,types:[],available:[]})}render()}});await Promise.all(workers);S.structural=[...S.catalog.values()].reduce((n,x)=>n+x.types.length*(x.types.length-1)/2,0);S.eligible=[...S.catalog.values()].filter(x=>x.types.some(t=>['CALL','PUT','DIGITEVEN','DIGITODD','DIGITOVER','DIGITUNDER','DIGITMATCH','DIGITDIFF'].includes(t))).map(x=>x.symbol);log(`Mapped ${S.symbols.length} symbols. ${S.eligible.length} currently support scoreable short-horizon contracts.`,'good');render()}
function wilson(w,n,z=1.64){if(!n)return 0;const p=w/n,z2=z*z,den=1+z2/n,centre=p+z2/(2*n),adj=z*Math.sqrt((p*(1-p)+z2/(4*n))/n);return Math.max(0,(centre-adj)/den)}
function quoteDigits(prices,pip){const decimals=Math.max(0,String(pip).split('.')[1]?.length||0),scale=10**decimals;return prices.map(x=>Math.abs(Math.round(Number(x)*scale))%10)}
function directionModel(symbol,prices,type,h=5){if(prices.length<80)return null;const signs=[];for(let i=1;i<prices.length;i++)signs.push(prices[i]>prices[i-1]?1:prices[i]<prices[i-1]?-1:0);const pattern=signs.slice(-3).join(',');let wins=0,n=0,recentW=0,recentN=0;for(let i=4;i<prices.length-h;i++){const pat=[signs[i-3],signs[i-2],signs[i-1]].join(',');if(pat!==pattern)continue;const delta=prices[i+h]-prices[i],win=type==='CALL'?delta>0:delta<0;n++;if(win)wins++;if(i>prices.length-180){recentN++;if(win)recentW++}}if(n<20)return null;return{key:`${symbol.code} · ${type} ${h}t`,symbol:symbol.code,symbolName:symbol.name,label:type==='CALL'?`Rise · ${h} ticks`:`Fall · ${h} ticks`,contractType:type,duration:h,durationUnit:'t',wins,sample:n,p:wins/n,lower:wilson(wins,n),recentP:recentN?recentW/recentN:wins/n}}
function digitModel(symbol,prices,pip,type,barrier=null){const digits=quoteDigits(prices,pip);if(digits.length<100)return null;const cur=digits[digits.length-1];let wins=0,n=0,recentW=0,recentN=0;for(let i=1;i<digits.length;i++){if(digits[i-1]!==cur)continue;const d=digits[i],win=type==='DIGITEVEN'?d%2===0:type==='DIGITODD'?d%2===1:type==='DIGITMATCH'?d===barrier:type==='DIGITDIFF'?d!==barrier:type==='DIGITOVER'?d>barrier:d<barrier;n++;if(win)wins++;if(i>digits.length-180){recentN++;if(win)recentW++}}if(n<25)return null;const name={DIGITEVEN:'Even',DIGITODD:'Odd',DIGITMATCH:`Match ${barrier}`,DIGITDIFF:`Differs ${barrier}`,DIGITOVER:`Over ${barrier}`,DIGITUNDER:`Under ${barrier}`}[type];return{key:`${symbol.code} · ${name}`,symbol:symbol.code,symbolName:symbol.name,label:name,contractType:type,duration:1,durationUnit:'t',barrier:barrier===null?null:String(barrier),wins,sample:n,p:wins/n,lower:wilson(wins,n),recentP:recentN?recentW/recentN:wins/n}}
async function history(symbol,count=650){const r=await request({ticks_history:symbol.code,end:'latest',count,style:'ticks'},12000),p=r?.history?.prices||[];return p.map(Number).filter(Number.isFinite)}
function buildModels(symbol,prices){const c=S.catalog.get(symbol.code),types=c?.types||[],out=[];if(types.includes('CALL')){const m=directionModel(symbol,prices,'CALL',5);if(m)out.push(m)}if(types.includes('PUT')){const m=directionModel(symbol,prices,'PUT',5);if(m)out.push(m)}if(types.includes('DIGITEVEN')){const m=digitModel(symbol,prices,symbol.pip,'DIGITEVEN');if(m)out.push(m)}if(types.includes('DIGITODD')){const m=digitModel(symbol,prices,symbol.pip,'DIGITODD');if(m)out.push(m)}if(types.includes('DIGITMATCH')){const digits=quoteDigits(prices,symbol.pip),cur=digits.at(-1),next=Array(10).fill(0);for(let i=1;i<digits.length;i++)if(digits[i-1]===cur)next[digits[i]]++;let best=0;for(let d=1;d<10;d++)if(next[d]>next[best])best=d;const m=digitModel(symbol,prices,symbol.pip,'DIGITMATCH',best);if(m)out.push(m)}if(types.includes('DIGITOVER')&&types.includes('DIGITUNDER'))for(const b of [2,3,4,5,6,7]){const a=digitModel(symbol,prices,symbol.pip,'DIGITOVER',b),u=digitModel(symbol,prices,symbol.pip,'DIGITUNDER',b);if(a)out.push(a);if(u)out.push(u)}return out}
async function scoreBatch(gen){if(!S.running||gen!==S.generation)return[];status('STATISTICAL TEST','Sampling recent tick history and estimating conditional outcomes.',3);const batch=[],take=Math.min(12,S.eligible.length);for(let i=0;i<take;i++){batch.push(S.eligible[S.symbolCursor%S.eligible.length]);S.symbolCursor++}let cursor=0;const found=[];const workers=Array.from({length:4},async()=>{while(cursor<batch.length&&S.running&&gen===S.generation){const symbol=batch[cursor++];try{const prices=await history(symbol);for(const m of buildModels(symbol,prices)){S.models.set(m.key,m);found.push(m)}}catch(e){log(`${symbol.code} history: ${e.message}`,'warn')}render()}});await Promise.all(workers);return found}
async function proposalFor(m){const req={proposal:1,amount:.35,basis:'stake',contract_type:m.contractType,currency:S.account?.currency||'USD',underlying_symbol:m.symbol,duration:m.duration,duration_unit:m.durationUnit};if(m.barrier!==null&&m.barrier!==undefined)req.barrier=m.barrier;const r=await request(req,8000),p=r?.proposal,ask=num(p?.ask_price),pay=num(p?.payout);if(!p?.id||ask===null||pay===null||pay<=0)throw Error('Incomplete proposal');const breakEven=ask/pay,expected=m.p*pay-ask,confExpected=m.lower*pay-ask;return{id:p.id,ask,payout:pay,breakEven,expected,confExpected}}
async function compareModels(models,gen){status('COMPARING','Pricing the strongest statistical candidates against live break-even odds.',4);const viable=models.filter(m=>!stats(m.key).dropped).sort((a,b)=>(b.p-b.lower)-(a.p-a.lower)).slice(0,35);const out=[];let cursor=0;const workers=Array.from({length:5},async()=>{while(cursor<viable.length&&S.running&&gen===S.generation){const m=viable[cursor++];try{const q=await proposalFor(m);S.quoted++;out.push({...m,proposal:q})}catch{}render()}});await Promise.all(workers);return out.sort((a,b)=>b.proposal.confExpected-a.proposal.confExpected||b.proposal.expected-a.proposal.expected)}
function classify(c){const st=stats(c.key),q=c.proposal,strong=c.sample>=60&&q.confExpected>0.002&&c.recentP>=q.breakEven-0.02,promising=c.sample>=25&&q.expected>0.002&&c.p>q.breakEven&&c.recentP>=q.breakEven-0.05,near=c.sample>=40&&q.expected>-0.01&&c.p>=q.breakEven-0.02&&c.recentP>=q.breakEven-0.04;if(st.trades>=3&&st.pnl>0&&st.wins/st.trades>=Math.max(.45,q.breakEven-0.04)&&promising)return'HARVEST';if(st.trades<3&&(strong||promising))return'PROBE';if(st.trades<2&&near)return'PROBE';return'WAIT'}
function shouldStop(best){if(S.pnl<=-2)return'Hard safety stop: session drawdown reached -$2.';if(S.sessionLossStreak>=5)return'Five consecutive Demo losses. Sani is stopping to avoid chasing.';if(S.trades>=40)return'Enough evidence for one run. Sani is stopping after 40 Demo trades.';if(S.pnl>=7)return'Sani is banking a strong session above +$7.';if(S.pnl>=3&&(!best||classify(best)==='WAIT'))return'Sani is banking the positive session because the edge has faded.';if(S.idleCycles>=8&&S.trades===0)return'No candidate came close enough for a useful Demo probe after eight fresh scans. Sani is resting.';if(S.idleCycles>=4&&S.trades>0)return'No worthwhile candidate survived four fresh scans. Sani is resting.';return''}
async function cycle(gen){if(!S.running||gen!==S.generation||S.active)return;const fresh=await scoreBatch(gen);if(!S.running||gen!==S.generation)return;const pool=[...S.models.values()].filter(m=>fresh.some(f=>f.key===m.key)||stats(m.key).trades>0),compared=await compareModels(pool,gen);if(!S.running||gen!==S.generation)return;status('CONFIDENCE TEST','Separating harvest candidates from small Demo probes.',5);const best=compared.find(c=>classify(c)!=='WAIT')||compared[0]||null,stopReason=shouldStop(best);if(stopReason){S.running=false;status('SANI SAYS STOP',stopReason,7);setDecision('STOP',stopReason,'rest');$('start').disabled=false;$('stop').disabled=true;render();return}if(!best){S.idleCycles++;setDecision('WAIT','No model could be priced cleanly this cycle. Sani will remap another batch.','rest');$('guide').innerHTML='<strong>Waiting.</strong> No clean statistical candidate this cycle.';S.timer=setTimeout(()=>cycle(gen),1600);return}best.mode=classify(best);S.current=best;render();if(best.mode==='WAIT'){S.idleCycles++;setDecision('WAIT',`Best candidate ${best.label} has model ${pct(best.p)} versus live break-even ${pct(best.proposal.breakEven)}, but it is not close enough for even a controlled Demo probe yet.`,'rest');$('guide').innerHTML='<strong>No trade this cycle.</strong> Sani is rotating to fresh markets instead of forcing an entry.';S.timer=setTimeout(()=>cycle(gen),1400);return}S.idleCycles=0;const mode=best.mode.toLowerCase();setDecision(best.mode,best.mode==='HARVEST'?'This model has survived at least three real Demo settlements with positive realized evidence, and the statistical/live-price edge still agrees. Sani will continue while that remains true.':'This is a small real Demo probe. It gathers settlement evidence before Sani can promote the model to Harvest.',mode);await enterTrade(best,gen)}
async function buy(c){const r=await request({buy:c.proposal.id,price:c.proposal.ask},10000),id=num(r?.buy?.contract_id);if(id===null)throw Error('Buy returned no contract ID');return{id,buyPrice:num(r?.buy?.buy_price)??c.proposal.ask,profit:0,done:false}}
async function enterTrade(c,gen){if(!S.running||gen!==S.generation)return;status(c.mode==='HARVEST'?'HARVESTING':'DEMO PROBE',`${c.label} on ${c.symbolName}. Stake $0.35. Sani will score the actual settlement before deciding what comes next.`,6);let leg;try{leg=await buy(c)}catch(e){log(`${c.key} buy failed · ${e.message}`,'warn');S.timer=setTimeout(()=>cycle(gen),900);return}S.active={candidate:c,leg};S.trades++;send({proposal_open_contract:1,contract_id:leg.id,subscribe:1,req_id:++S.req});log(`${c.mode} OPEN · ${c.key} · model ${pct(c.p)} · BE ${pct(c.proposal.breakEven)} · expected ${money(c.proposal.expected)}`,'good');render()}
function contractUpdate(m){if(!S.active)return;const c=m?.proposal_open_contract,id=num(c?.contract_id);if(id!==S.active.leg.id)return;const leg=S.active.leg;leg.profit=num(c?.profit)??leg.profit;const done=!!c?.is_sold||['won','lost','sold','expired'].includes(String(c?.status||'').toLowerCase());if(!done)return;const candidate=S.active.candidate,profit=leg.profit||0,st=stats(candidate.key);st.trades++;st.pnl+=profit;if(profit>0){st.wins++;st.lossStreak=0;S.wins++;S.sessionLossStreak=0}else{st.losses++;st.lossStreak++;S.losses++;S.sessionLossStreak++}if(st.lossStreak>=3||(st.trades>=5&&st.pnl<-.35)){if(!st.dropped){st.dropped=true;S.dropped++;log(`AUTO-DROP · ${candidate.key} · ${st.trades} trades · ${money(st.pnl)}`,'bad')}}saveStats(candidate.key,st);S.pnl+=profit;S.active=null;log(`SETTLED · ${candidate.key} · ${money(profit)} · model total ${money(st.pnl)}`,profit>0?'good':'bad');render();if(S.running)S.timer=setTimeout(()=>cycle(S.generation),650);else{status('STOPPED','The open Demo trade has settled. Sani is fully stopped.');setDecision('STOP','No open Demo trades remain.','rest');$('start').disabled=false;$('stop').disabled=true;render()}}
async function start(){if(S.running||S.starting||S.active)return;S.starting=true;$('start').disabled=true;$('stop').disabled=false;S.pnl=0;S.trades=0;S.wins=0;S.losses=0;S.sessionLossStreak=0;S.idleCycles=0;S.quoted=0;S.dropped=0;S.current=null;S.models.clear();S.modelStats.clear();S.symbolCursor=0;S.generation++;const gen=S.generation;try{await loadSession();await connect();S.running=true;await mapUniverse();if(!S.eligible.length)throw Error('No scoreable short-horizon contracts are available right now.');status('STRUCTURAL TEST','Cataloguing contract families and filtering what can be statistically scored without pretending it is arbitrage.',2);await sleep(250);render();await cycle(gen)}catch(e){S.running=false;status('CANNOT START',e.message);setDecision('STOP',e.message,'rest');$('start').disabled=false;$('stop').disabled=true}finally{S.starting=false}}
function stop(){S.running=false;S.generation++;clearTimeout(S.timer);if(S.active){status('STOPPING','No new Demo entries will be sent. Sani is waiting for the currently open Demo contract to settle.');setDecision('STOP AFTER SETTLEMENT','One Demo contract is still open. Sani will not start another run until it settles.','rest');$('start').disabled=true;$('stop').disabled=true}else{status('STOPPED','You stopped Sani. No new Demo entries will be sent.');setDecision('STOP','Manual stop.','rest');$('start').disabled=false;$('stop').disabled=true}render()}
$('start').onclick=start;$('stop').onclick=stop;
(async()=>{try{await loadSession();status('READY','Press Start Sani. Demo probes are real Demo contracts, not simulated trades.')}catch{status('LOGIN REQUIRED','Login with Deriv first. Demo only.')}setDecision('WAIT','Ready for a fresh edge-lab run.','rest');render()})();